#!/usr/bin/env bash

set -uo pipefail

GITDIR=~/temp

cd "${GITDIR}" || {
  echo "Missing ${GITDIR}"
  exit 1
}

git clone --depth 1 https://git.sr.ht/~bzg/worg
git clone --depth 1 git://git.etalabs.net/musl
git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
git clone --depth 1 git://git.suckless.org/9base
git clone --depth 1 git://git.suckless.org/blind
git clone --depth 1 git://git.suckless.org/dwm
git clone --depth 1 git://git.suckless.org/ii
git clone --depth 1 git://git.suckless.org/lchat
git clone --depth 1 git://git.suckless.org/libsl
git clone --depth 1 git://git.suckless.org/quark
git clone --depth 1 git://git.suckless.org/sbase
git clone --depth 1 git://git.suckless.org/sinit
git clone --depth 1 git://git.suckless.org/smdev
git clone --depth 1 git://git.suckless.org/surf
git clone --depth 1 git://git.suckless.org/tabbed
git clone --depth 1 git://git.suckless.org/ubase
git clone --depth 1 git://git.suckless.org/utmp
git clone --depth 1 http://github.com/banchose/patching
git clone --depth 1 https://codeberg.org/dnkl/foot.git
git clone --depth 1 https://gist.github.com/9to5IT/9620683
git clone --depth 1 https://gist.github.com/MohamedAlaa/2961058#file-tmux-cheatsheet-markdown
git clone --depth 1 https://github.com/0xAX/linux-insides
git clone --depth 1 https://github.com/1amSimp1e/dots
git clone --depth 1 https://github.com/a13xp0p0v/linux-kernel-defence-map
git clone --depth 1 https://github.com/acmesh-official/acme.sh
git clone --depth 1 https://github.com/alebcay/awesome-shell
git clone --depth 1 https://github.com/alexanderepstein/Bash-Snippets
git clone --depth 1 https://github.com/algorithm-visualizer/algorithm-visualizer
git clone --depth 1 https://github.com/algorithm-visualizer/algorithm-visualizer.wiki.git
git clone --depth 1 https://github.com/alijahnas/CKA-practice-exercises.git
git clone --depth 1 https://github.com/alphapapa/solarized-everything-css
git clone --depth 1 https://github.com/anordal/shellharden
git clone --depth 1 https://github.com/anthropics/anthropic-cookbook
git clone --depth 1 https://github.com/arkenfox/user.js/
git clone --depth 1 https://github.com/astronvim/astronvim.wiki.git
git clone --depth 1 https://github.com/Atinoda/text-generation-webui-docker
git clone --depth 1 https://github.com/awesome-lists/awesome-bash
git clone --depth 1 https://github.com/Awesome-Windows/Awesome
git clone --depth 1 https://github.com/aws-ia/cfn-ps-cisco-meraki-vmx-cloudwan
git clone --depth 1 https://github.com/aws-quickstart/taskcat
git clone --depth 1 https://github.com/aws-samples/aws-networkfirewall-cfn-templates
git clone --depth 1 https://github.com/aws-samples/aws-vpc-builder-cdk
git clone --depth 1 https://github.com/aws-samples/multi-account-az-mapping/
git clone --depth 1 https://github.com/Aylur/ags
git clone --depth 1 https://github.com/bagder/everything-curl
git clone --depth 1 https://github.com/bagder/everything-curl
git clone --depth 1 https://github.com/banchose/aws
git clone --depth 1 https://github.com/banchose/awscfts.git
git clone --depth 1 https://github.com/banchose/aws-inspect-network
git clone --depth 1 https://github.com/banchose/aws-stacksets
git clone --depth 1 https://github.com/banchose/configs
git clone --depth 1 https://github.com/banchose/drawio
git clone --depth 1 https://github.com/banchose/ffuser
git clone --depth 1 https://github.com/banchose/gitscripts.git
git clone --depth 1 https://github.com/banchose/learngit
git clone --depth 1 https://github.com/banchose/myc
git clone --depth 1 https://github.com/banchose/mydoc
git clone --depth 1 https://github.com/banchose/mymake
git clone --depth 1 https://github.com/banchose/mymodule
git clone --depth 1 https://github.com/banchose/myprog
git clone --depth 1 https://github.com/banchose/myprog
git clone --depth 1 https://github.com/banchose/skel
git clone --depth 1 https://github.com/banchose/srm
git clone --depth 1 https://github.com/banchose/tf
git clone --depth 1 https://github.com/basarat/typescript-book
git clone --depth 1 https://github.com/bat/bat.wiki.git
git clone --depth 1 https://github.com/beejjorgensen/bgc.git
git clone --depth 1 https://github.com/bjesus/wttrbar
git clone --depth 1 https://github.com/bminor/bash
git clone --depth 1 https://github.com/bolinfest/opensnoop-native
git clone --depth 1 https://github.com/bpftools/linux-observability-with-bpf
git clone --depth 1 https://github.com/bradtraversy/50projects50days
git clone --depth 1 https://github.com/brainfucksec/neovim-lua
git clone --depth 1 https://github.com/brandongooch/apue.3e
git clone --depth 1 https://github.com/bregman-arie/devops-exercises
git clone --depth 1 https://github.com/BruceDone/awesome-crawler
git clone --depth 1 https://github.com/cfenollosa/os-tutorial
git clone --depth 1 https://github.com/chrisdone/elisp-guide
git clone --depth 1 https://github.com/cirosantilli/linux-cheat
git clone --depth 1 https://github.com/cirosantilli/linux-kernel-module-cheat
git clone --depth 1 https://github.com/CISOfy/lynis
git clone --depth 1 https://github.com/codeplea/hands-on-network-programming-with-c
git clone --depth 1 https://github.com/collabnix/kubetools
git clone --depth 1 https://github.com/commonmark/cmark
git clone --depth 1 https://github.com/containers/crun
git clone --depth 1 https://github.com/coodict/javascript-in-one-pic
git clone --depth 1 https://github.com/coodict/python3-in-one-pic
git clone --depth 1 https://github.com/coreutils/coreutils.wiki.git
git clone --depth 1 https://github.com/danistefanovic/build-your-own-x
git clone --depth 1 https://github.com/danny-avila/LibreChat.git
git clone --depth 1 https://github.com/darius/code-canon
git clone --depth 1 https://github.com/dcecchino/glog
git clone --depth 1 https://github.com/denysdovhan/bash-handbook
git clone --depth 1 https://github.com/derekmolloy/exploringBB.git
git clone --depth 1 https://github.com/Developer-Y/cs-video-courses
git clone --depth 1 https://github.com/dgomesbr/awesome-aws-workshops
git clone --depth 1 https://github.com/dictcp/awesome-git
git clone --depth 1 https://github.com/diejuse/pseudo3dbash
git clone --depth 1 https://github.com/DoctorWkt/acwj
git clone --depth 1 https://github.com/donnemartin/awesome-aws
git clone --depth 1 https://github.com/doomemacs/doomemacs.wiki.git
git clone --depth 1 https://github.com/druskus20/eugh
git clone --depth 1 https://github.com/drwetter/testssl.sh
git clone --depth 1 https://github.com/DSheirer/sdrtrunk
git clone --depth 1 https://github.com/EliverLara/Sweet
git clone --depth 1 https://github.com/EmilyShepherd/covid-checker
git clone --depth 1 https://github.com/end-4/dots-hyprland
git clone --depth 1 https://github.com/eoli3n/dotfiles
git clone --depth 1 https://github.com/EONRaider/BCA-Phantom.git
git clone --depth 1 https://github.com/erikdubois/arcolinux-nemesis
git clone --depth 1 https://github.com/EvotecIT/PSWinReporting
git clone --depth 1 https://github.com/f/awesome-chatgpt-prompts
git clone --depth 1 https://github.com/fcambus/nginx-resources
git clone --depth 1 https://github.com/Fechin/reference
git clone --depth 1 https://github.com/flick0/dotfiles
git clone --depth 1 https://github.com/folke/tokyonight.nvim
git clone --depth 1 https://github.com/for-GET/http-decision-diagram.git
git clone --depth 1 https://github.com/fragglet/c-algorithms
git clone --depth 1 https://github.com/Friz-zy/awesome-linux-containers.git
git clone --depth 1 https://github.com/garyexplains/examples
git clone --depth 1 https://github.com/git/git
git clone --depth 1 https://github.com/github/cmark-gfm
git clone --depth 1 https://github.com/github/gitignore
git clone --depth 1 https://github.com/Gogh-Co/Gogh
git clone --depth 1 https://github.com/groovemonkey/project-based-kubernetes
git clone --depth 1 https://github.com/Hack-with-Github/Awesome-Hacking
git clone --depth 1 https://github.com/herrbischoff/awesome-command-line-apps
git clone --depth 1 https://github.com/herrbischoff/awesome-macos-command-line
git clone --depth 1 https://github.com/hyprwm/contrib
git clone --depth 1 https://github.com/hyprwm/Hyprland
git clone --depth 1 https://github.com/id-Software/DOOM
git clone --depth 1 https://github.com/Igglybuff/awesome-piracy
git clone --depth 1 https://github.com/illinois-cs241/coursebook.git
git clone --depth 1 https://github.com/imomaliev/tmux-bash-completion
git clone --depth 1 https://github.com/iovisor/bcc
git clone --depth 1 https://github.com/iovisor/bpf-docs
git clone --depth 1 https://github.com/iovisor/bpftrace
git clone --depth 1 https://github.com/iptv-org/iptv
git clone --depth 1 https://github.com/isocpp/CppCoreGuidelines
git clone --depth 1 https://github.com/jakehamilton/dotfiles
git clone --depth 1 https://github.com/jamesrmoro/the-status-rebellion
git clone --depth 1 https://github.com/janikvonrotz/awesome-powershell
git clone --depth 1 https://github.com/jassics/awesome-aws-security
git clone --depth 1 https://github.com/jaywcjlove/awesome-mac
git clone --depth 1 https://github.com/jborza/solitaire-cli
git clone --depth 1 https://github.com/jbsky/graylog
git clone --depth 1 https://github.com/jedisct1/libsodium
git clone --depth 1 https://github.com/jeffgerickson/algorithms
git clone --depth 1 https://github.com/jnv/lists
git clone --depth 1 https://github.com/jnv/lists.git
git clone --depth 1 https://github.com/joelshepherd/tabliss
git clone --depth 1 https://github.com/jointhefediverse-net/jointhefediverse.net
git clone --depth 1 https://github.com/joyeusenoelle/GuideToMastodon/
git clone --depth 1 https://github.com/jpetazzo/container.training
git clone --depth 1 https://github.com/jqlang/jq.wiki.git
git clone --depth 1 https://github.com/jwasham/coding-interview-university
git clone --depth 1 https://github.com/k88hudson/git-flight-rules
git clone --depth 1 https://github.com/k88hudson/git-flight-rules
git clone --depth 1 https://github.com/kalaiser/awesome-cdk
git clone --depth 1 https://github.com/keenanromain/AWS-SAA-C02-Study-Guide
git clone --depth 1 https://github.com/kelseyhightower/kubernetes-the-hard-way
git clone --depth 1 https://github.com/kettanaito/naming-cheatsheet
git clone --depth 1 https://github.com/kislyuk/yq
git clone --depth 1 https://github.com/kubernetes/ingress-nginx
git clone --depth 1 https://github.com/kubernetes-sigs/metrics-server
git clone --depth 1 https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
git clone --depth 1 https://github.com/kvz/bash3boilerplate
git clone --depth 1 https://github.com/laurent22/joplin.git
git clone --depth 1 https://github.com/lawrencesystems/graylog
git clone --depth 1 https://github.com/lawrencesystems/graylog_extractors
git clone --depth 1 https://github.com/LeCoupa/awesome-cheatsheets
git clone --depth 1 https://github.com/lee88688/aider-composer
git clone --depth 1 https://github.com/lhunath/guide.bash.academy
git clone --depth 1 https://github.com/libusb/hidapi
git clone --depth 1 https://github.com/linuxmobile/hyprland-dots
git clone --depth 1 https://github.com/ljacobsson/cfn-diagram
git clone --depth 1 https://github.com/lokesh-krishna/dotfiles
git clone --depth 1 https://github.com/lunarvim/neovim-from-scratch
git clone --depth 1 https://github.com/luongvo209/Awesome-Linux-Software
git clone --depth 1 https://github.com/m4xshen/dotfiles
git clone --depth 1 https://github.com/maltfield/awesome-lemmy-instances
git clone --depth 1 https://github.com/mantvydasb/RedTeam-Tactics-and-Techniques
git clone --depth 1 https://github.com/MatMoul/g810-led
git clone --depth 1 https://github.com/maximbaz/dotfiles
git clone --depth 1 https://github.com/maxogden/art-of-node
git clone --depth 1 https://github.com/mechaniac/Map-of-Javascript
git clone --depth 1 https://github.com/metal3d/bashsimplecurses
git clone --depth 1 https://github.com/Microsoft/Ethr
git clone --depth 1 https://github.com/microsoft/PowerToys
git clone --depth 1 https://github.com/microsoft/TypeScript-Website
git clone --depth 1 https://github.com/mikeroyal/Linux-Guide
git clone --depth 1 https://github.com/mjlbach/defaults.nvim.git
git clone --depth 1 https://github.com/moimikey/awesome-devtools
git clone --depth 1 https://github.com/MunGell/awesome-for-beginners
git clone --depth 1 https://github.com/nanotee/nvim-lua-guide
git clone --depth 1 https://github.com/nathanpeck/awesome-ecs
git clone --depth 1 https://github.com/nemanja-jovic/powershell4all
git clone --depth 1 https://github.com/neovim/neovim
git clone --depth 1 https://github.com/neovim/neovim.wiki.git
git clone --depth 1 https://github.com/nerab/manbook
git clone --depth 1 https://github.com/neural75/gqrx-scanner
git clone --depth 1 https://github.com/nginxinc/kubernetes-ingress.git
git clone --depth 1 https://github.com/nginx/nginx
git clone --depth 1 https://github.com/nicolaka/netshoot
git clone --depth 1 https://github.com/niyumard/Doom-Emacs-Cheat-Sheet
git clone --depth 1 https://github.com/numToStr/dotfiles
git clone --depth 1 https://github.com/nvim-lua/kickstart.nvim
git clone --depth 1 https://github.com/nvim-lua/lsp-status.nvim
git clone --depth 1 https://github.com/nvim-lua/plenary.nvim
git clone --depth 1 https://github.com/occivink/mpv-scripts
git clone --depth 1 https://github.com/oitofelix/pil-4th
git clone --depth 1 https://github.com/ollama/ollama
git clone --depth 1 https://github.com/onceupon/Bash-Oneliner
git clone --depth 1 https://github.com/open-source-parsers/jsoncpp.git
git clone --depth 1 https://github.com/openzfs/zfs
git clone --depth 1 https://github.com/ossu/computer-science
git clone --depth 1 https://github.com/OWASP/CheatSheetSeries
git clone --depth 1 https://github.com/ozbillwang/terraform-best-practices
git clone --depth 1 https://github.com/PacktPublishing/Hands-On-System-Programming-with-CPP
git clone --depth 1 https://github.com/parrot/parrot.wiki.git
git clone --depth 1 https://github.com/pbatard/parrot
git clone --depth 1 https://github.com/petersem/dockerholics
git clone --depth 1 https://github.com/Photon/Photon.wiki.git
git clone --depth 1 https://github.com/pistazie/cdk-dia
git clone --depth 1 https://github.com/pluja/awesome-privacy
git clone --depth 1 https://github.com/praetorian-inc/noseyparker
git clone --depth 1 https://github.com/prakhar1989/awesome-courses
git clone --depth 1 https://github.com/progit/progit2
git clone --depth 1 https://github.com/progrium/bashstyle
git clone --depth 1 https://github.com/ralish/bash-script-template
git clone --depth 1 https://github.com/Randy8080/reference # quickref
git clone --depth 1 https://github.com/rby90/Project-Based-Tutorials-in-C
git clone --depth 1 https://github.com/redis/redis
git clone --depth 1 https://github.com/REMitchell/python-scraping
git clone --depth 1 https://github.com/rockerBOO/awesome-neovimmakefile
git clone --depth 1 https://github.com/rodrigobdz/docker-compose-healthchecks
git clone --depth 1 https://github.com/rubenlagus/TelegramBots
git clone --depth 1 https://github.com/rust-lang/book
git clone --depth 1 https://github.com/rustyrussell/ccan/
git clone --depth 1 https://github.com/s0md3v/Photon
git clone --depth 1 https://github.com/seblegall/bash-script-options-boilerplate.git
git clone --depth 1 https://github.com/sevagh/namespace-experiments
git clone --depth 1 https://github.com/sezanzeb/input-remapper
git clone --depth 1 https://github.com/sharkdp/bat
git clone --depth 1 https://github.com/shemminger/iproute2
git clone --depth 1 https://github.com/SillyTavern/SillyTavern
git clone --depth 1 https://github.com/SimpleHomelab/docker-traefik
git clone --depth 1 https://github.com/sindresorhus/awesome
git clone --depth 1 https://github.com/sindresorhus/awesome-nodejs
git clone --depth 1 https://github.com/sivel/speedtest-cli
git clone --depth 1 https://github.com/slacka/WoeUSB
git clone --depth 1 https://github.com/s-matyukevich/raspberry-pi-os
git clone --depth 1 https://github.com/snaptoken/kilo-tutorial
git clone --depth 1 https://github.com/soulteary/llama-docker-playground
git clone --depth 1 https://github.com/stedolan/jq
git clone --depth 1 https://github.com/strongjz/Networking-and-Kubernetes
git clone --depth 1 https://github.com/swaywm/sway
git clone --depth 1 https://github.com/swaywm/wlroots/tree/master/tinywl
git clone --depth 1 https://github.com/Sycnex/Windows10Debloater.git
git clone --depth 1 https://github.com/systemd/systemd
git clone --depth 1 https://github.com/szechyjs/mbelib
git clone --depth 1 https://github.com/tborychowski/self-hosted-cookbook
git clone --depth 1 https://github.com/techiescamp/kubernetes-learning-path
git clone --depth 1 https://github.com/terraform-in-action/manning-code
git clone --depth 1 https://github.com/tessus/joplin-scripts.git
git clone --depth 1 https://github.com/testssl/testssl.sh.git
git clone --depth 1 https://github.com/Textualize/rich
git clone --depth 1 https://github.com/TheAlgorithms/C
git clone --depth 1 https://github.com/TheAlgorithms/C-Plus-Plus
git clone --depth 1 https://github.com/TheAlgorithms/Javascript
git clone --depth 1 https://github.com/tleb/awesome-mastodon
git clone --depth 1 https://github.com/tmux/tmux
git clone --depth 1 https://github.com/tmux/tmux.wiki.git
git clone --depth 1 https://github.com/tokenrove/build-your-own-shell
git clone --depth 1 https://github.com/topics/bookmarklets
git clone --depth 1 https://github.com/torvalds/linux
git clone --depth 1 https://github.com/traefik/traefik
git clone --depth 1 https://github.com/trailofbits/algo # wireguard
git clone --depth 1 https://github.com/trimstray/htrace.sh
git clone --depth 1 https://github.com/trimstray/iptables-essentials
git clone --depth 1 https://github.com/trimstray/nginx-admins-handbook
git clone --depth 1 https://github.com/trimstray/the-book-of-secret-knowledge.git
git clone --depth 1 https://github.com/typicode/json-server
git clone --depth 1 https://github.com/UltimateHackers/Decodify
git clone --depth 1 https://github.com/universal-ctags/ctags
git clone --depth 1 https://github.com/uutils/coreutils
git clone --depth 1 https://github.com/vdjagilev/nmap-formatter
git clone --depth 1 https://github.com/veggiemonk/awesome-docker
git clone --depth 1 https://github.com/ventoy/Ventoy
git clone --depth 1 https://github.com/VernonGrant/emacs-keyboard-shortcuts
git clone --depth 1 https://github.com/viatsko/awesome-vscode
git clone --depth 1 https://github.com/vladwa/kuberenetes-kubectl-cheatsheet
git clone --depth 1 https://github.com/vmware/PowerCLI-Example-Scripts
git clone --depth 1 https://github.com/VonHeikemen/nvim-starter
git clone --depth 1 https://github.com/w4rh4wk/debloat-windows-10
git clone --depth 1 https://github.com/webpro/awesome-dotfiles
git clone --depth 1 https://github.com/WerWolv/ImHex
git clone --depth 1 https://github.com/widdix/aws-cf-templates
git clone --depth 1 https://github.com/wireservice/csvkit
git clone --depth 1 https://github.com/WoeUSB/WoeUSB.wiki.git
git clone --depth 1 https://github.com/w-vi/diyC.git
git clone --depth 1 https://github.com/xwmx/bash-boilerplate
git clone --depth 1 https://github.com/yadutaf/tracepkt
git clone --depth 1 https://github.com/yasoob/intermediatePython
git clone --depth 1 https://github.com/yt-dlp/yt-dlp
git clone --depth 1 https://github.com/Z4nzu/hackingtool
git clone --depth 1 https://github.com/Zeioth/zeioth-hyprland-config
git clone --depth 1 https://github.com/zellij-org/zellij
git clone --depth 1 https://github.com/ziishaned/learn-regex
git clone --depth 1 https://gitlab.com/archmirak/archlinux-fde-uefi.git
git clone --depth 1 https://gitlab.com/cryptsetup/cryptsetup.git
git clone --depth 1 https://gitlab.com/khaytsus/gqrx-scan
git clone --depth 1 https://git.savannah.gnu.org/git/emacs/org-mode.git
git clone --depth 1 https://git.savannah.gnu.org/git/grub.git
git clone --depth 1 https://git.sr.ht/~emersion/chayang
git clone --depth 1 https://git.suckless.org/st
git clone --depth 1 https://www.bearssl.org/git/BearSSL
