services:
  seafile:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seafile.rule=Host(`seafile.xaax.dev`)"
      - "traefik.http.routers.seafile.entrypoints=websecure"
      - "traefik.http.routers.seafile.tls=true"
      - "traefik.http.services.seafile.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik_web"
    networks:
      - traefik_web
      - default

networks:
  traefik_web:
    external: true

