network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: no
      addresses:
      - 192.168.122.10/24
      routes:
      - to: 0.0.0.0/0
        via: 192.168.122.1
      nameservers:
        addresses: [192.168.122.1, 8.8.4.4]
