version: '3'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-config:/etc/traefik  # Local directory mapped to container path
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"  # Path inside container
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
