apiVersion: v1
kind: Namespace
metadata:
  name: librechat

---
apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
stringData:
  CREDS_KEY: 5df0c9e5df
  JWT_SECRET: d22dc4f18
  JWT_REFRESH_SECRET: 264
  MEILI_MASTER_KEY: 53d0
