pageInfo:
  title: Hello, Una
  description: General browser startpage
  logo: https://i.ibb.co/71WyyzM/little-bot-3.png
appConfig:
  statusCheck: false
  theme: colorful
  fontAwesomeKey: c94dc2b452
  customCss: '.clock p.time { font-size: 3rem !important; }'
  layout: vertical
  iconSize: large
sections:
  - name: Today
    icon: far fa-smile-beam
    displayData:
      collapsed: false
      hideForGuests: false
    widgets:
      - type: clock
        id: 0_513_clock
      - type: weather
        options:
          apiKey: efdbade728b37086877a5e83442004db
          city: London
        id: 1_513_weather
      - type: crypto-watch-list
        options:
          currency: GBP
          sortBy: marketCap
          assets:
            - bitcoin
            - ethereum
            - monero
            - solana
            - polkadot
        id: 2_513_cryptowatchlist
  - name: Productivity
    icon: far fa-briefcase
    items:
      - title: CTemplar
        icon: favicon
        url: https://mail.ctemplar.com/
        description: Secondary email account
        tags:
          - hosted
          - personal
          - email
          - mail
        hotkey: 2
        id: 0_1302_ctemplar
      - title: AnonAddy
        icon: favicon
        url: https://app.anonaddy.com/
        description: Mail alias forwarder
        tags:
          - hosted
          - personal
          - forwarder
          - aliases
          - email
        hotkey: 3
        statusCheckAcceptCodes: '401'
        id: 1_1302_anonaddy
      - title: Tresorit
        icon: favicon
        url: https://web.tresorit.com/
        description: Off-site encrypted file sync + backup
        tags:
          - hosted
          - personal
          - files
          - backup
          - sync
          - storage
        hotkey: 7
        id: 2_1302_tresorit
  - name: Dev & Cloud
    icon: far fa-code
    items:
      - title: GitHub
        icon: favicon
        url: https://github.com/
        id: 0_892_github
      - title: StackOverflow
        icon: favicon
        url: http://stackoverflow.com/
        id: 1_892_stackoverflow
      - title: CloudFlare
        icon: favicon
        url: https://dash.cloudflare.com/
        statusCheckAcceptCodes: '403'
        id: 2_892_cloudflare
      - title: DigitalOcean
        icon: favicon
        url: https://cloud.digitalocean.com/
        id: 3_892_digitalocean
      - title: CodeSandbox
        icon: favicon
        url: https://codesandbox.io/dashboard
        id: 4_892_codesandbox
      - title: Documentation
        subItems:
          - title: JavaScript
            url: https://developer.mozilla.org
            icon: si-javascript
            color: '#F7DF1E'
          - title: TypeScript
            url: https://www.typescriptlang.org/docs
            icon: si-typescript
            color: '#3178C6'
          - title: Svelt
            url: https://svelte.dev/docs
            icon: si-svelte
            color: '#FF3E00'
          - title: Go
            url: https://go.dev/doc
            icon: si-go
            color: '#00ADD8'
          - title: Rust
            url: https://doc.rust-lang.org/reference
            icon: si-rust
            color: '#000000'
          - title: Docker
            url: https://docs.docker.com/
            icon: si-docker
            color: '#2496ED'
        id: 5_892_documentation
  - name: Social & News
    icon: far fa-thumbs-up
    items:
      - title: Discord
        icon: si-discord
        url: https://discord.com/channels/
        id: 0_1118_discord
      - title: Mastodon
        icon: si-mastodon
        url: https://mastodon.social/
        id: 1_1118_mastodon
      - title: Reddit
        icon: si-reddit
        url: https://www.reddit.com/
        id: 2_1118_reddit
      - title: HackerNews
        icon: si-ycombinator
        url: https://news.ycombinator.com/
        id: 3_1118_hackernews
      - title: Twitter
        icon: si-twitter
        url: https://twitter.com/
        id: 4_1118_twitter
      - title: Instagram
        icon: si-instagram
        url: https://www.instagram.com/
        id: 5_1118_instagram
      - title: News
        icon: si-bbc
        url: https://bbc.co.uk/news
        id: 6_1118_news
      - title: Crypto Prices
        icon: fab fa-bitcoin
        url: https://www.livecoinwatch.com/
        description: Real-time crypto prices and read-only portfolio
        provider: Live Coin Watch
        id: 7_1118_cryptoprices
      - title: Drudge
        description: Headlines
        url: https://www.drudgereport.com
        target: parent
        id: 8_1118_drudge
      - title: TEST
        url: http://www.cnn.com
        target: newtab
        id: 9_1118_test
