services:
  privatebin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.privatebin.rule=Host(`privatebin.xaax.dev`)"
      - "traefik.http.routers.privatebin.entrypoints=websecure"
      - "traefik.http.routers.privatebin.tls=true"
      - "traefik.http.services.privatebin.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_web"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
