services:
  privatebin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.privatebin.rule=Host(`privatebin.xaax.dev`)"
      - "traefik.http.routers.privatebin.entrypoints=websecure"
      - "traefik.http.routers.privatebin.tls=true"
      - "traefik.http.services.privatebin.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_web"
    healthcheck:
      test: wget --spider http://127.0.0.1:8080
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
