# NOTE: 
# sftp -P 2222 star
# mind the capital P
services:
    sftpgo:
      container_name: sftpgo
      labels:
        # Basic HTTP routing - simplifying to get it working
        - "traefik.enable=true"
        - "traefik.http.routers.sftpgo.rule=Host(`sftpgo.xaax.dev`)"
        - "traefik.http.routers.sftpgo.entrypoints=websecure"
        - "traefik.http.routers.sftpgo.tls=true"
        - "traefik.http.services.sftpgo.loadbalancer.server.port=8080"
        
        # Make sure there's no middleware causing issues
        # - "traefik.http.routers.sftpgo.middlewares=sftpgo-health@docker"
        
        # TCP routing for SFTP service
        - "traefik.tcp.routers.sftpgo-sftp.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.sftpgo-sftp.entrypoints=sftp"
        - "traefik.tcp.routers.sftpgo-sftp.service=sftpgo-sftp-service"
        - "traefik.tcp.services.sftpgo-sftp-service.loadbalancer.server.port=2022"
        # WebDAV routing
#       - "traefik.http.routers.sftpgo-webdav.rule=Host(`webdav.xaax.dev`)"
#       - "traefik.http.routers.sftpgo-webdav.entrypoints=websecure"
#       - "traefik.http.routers.sftpgo-webdav.tls=true"
#       - "traefik.http.services.sftpgo-webdav.loadbalancer.server.port=10080"
 
        - "traefik.docker.network=traefik_web"

      environment: #
#       - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
#       - SFTPGO_HTTPD__BINDINGS__0__ADDRESS=0.0.0.0
#       - SFTPGO_DATA__PROVIDER__CREATE__DEFAULT__ADMIN=true
        - SFTPGO_WEBDAVD__ENABLED=true
#       - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
#       - SFTPGO_WEBDAVD__BINDINGS__0__ADDRESS=0.0.0.0

        - SFTPGO_SFTPD__ENABLED=true
        - SFTPGO_SFTPD__BINDINGS__0__PORT=2022
        - SFTPGO_SFTPD__BINDINGS__0__ADDRESS=0.0.0.0

#       - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
#       - SFTPGO_HTTPD__BINDINGS__0__ADDRESS=0.0.0.0  # Remove underscore at beginning
#       - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true  # Fixed format
#       # Remove these if they're causing issues
#       # - SFTPGO_HTTPD__TEMPLATES_PATH=/templates
#       # - SFTPGO_HTTPD__STATIC_FILES_PATH=/static
#       - SFTPGO_WEBDAVD__ENABLED=true
#       - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
#       - SFTPGO_WEBDAVD__BINDINGS__0__ADDRESS=0.0.0.0  # Added missing address
#       - SFTPGO_FTPD__BINDINGS__0__PORT=2121
#       - SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=sftpgo.xaax.dev  # Fixed format
#       # SFTP configuration - ADD THESE LINES
#       - SFTPGO_SFTPD__ENABLED=true  # Fixed (removed extra underscore)
#       - SFTPGO_SFTPD__BINDINGS__0__PORT=2022  # Fixed (removed extra underscore)
#       - SFTPGO_SFTPD__BINDINGS__0__ADDRESS=0.0.0.0  # Fixed (removed extra underscore)
#       - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
#       - SFTPGO_HTTPD__BINDINGS__0__ADDRESS=0.0.0.0
#       - SFTPGO_DATA__PROVIDER__CREATE__DEFAULT__ADMIN=true
#       # Remove these if they're causing issues
#       # - SFTPGO_HTTPD__TEMPLATES_PATH=/templates
#       # - SFTPGO_HTTPD__STATIC_FILES_PATH=/static
#       - SFTPGO_WEBDAVD__ENABLED=true
#       - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
#       - SFTPGO_FTPD__BINDINGS__0__PORT=2121
#       - SFTPGO_FTPD__BINDINGS__0_FORCE__PASSIVE__IP=sftpgo.xaax.dev
#           # SFTP configuration - ADD THESE LINES
#       - SFTPGO_SFTPD___ENABLED=true
#       - SFTPGO_SFTPD___BINDINGS__0__PORT=2022
#       - SFTPGO_SFTPD___BINDINGS__0__ADDRESS=0.0.0.0

      networks:
        - traefik_web
      volumes:
        - sftpgo_data:/var/lib/sftpgo
        - sftpgo_config:/etc/sftpgo
        - sftpgo_home:/srv/sftpgo/data

volumes:
  sftpgo_data:
  sftpgo_config:
  sftpgo_home:

networks:
  traefik_web:
    external: true
