services:
    sftpgo:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sftpgo.rule=Host(`sftpgo.xaax.dev`)"
        - "traefik.http.routers.sftpgo.entrypoints=websecure"
        - "traefik.http.routers.sftpgo.tls=true"
        - "traefik.http.services.sftpgo.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik_web"
      networks:
        - traefik_web
      volumes:
        - sftpgo_data:/var/lib/sftpgo
        - sftpgo_config:/etc/sftpgo
        - sftpgo_home:/srv/sftpgo/data

volumes:
  sftpgo_data:
  sftpgo_config:
  sftpgo_home:

networks:
  traefik_web:
    external: true
