services:
  web-check:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-check.rule=Host(`web-check.xaax.dev`)"
      - "traefik.http.routers.web-check.entrypoints=websecure"
      - "traefik.http.routers.web-check.tls=true"
      - "traefik.http.services.web-check.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_web"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
