services:
  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat.rule=Host(`xaax.dev`)"
      - "traefik.http.routers.librechat.entrypoints=websecure"
      - "traefik.http.routers.librechat.tls=true"
      - "traefik.http.services.librechat.loadbalancer.server.port=3080"
    networks:
      - traefik_network
    volumes:
      - ./librechat.yaml:/app/librechat.yaml

  # Add MongoDB to the network
  mongodb:
    networks:
      - traefik_network

  # Add Meilisearch to the network
  meilisearch:
    networks:
      - traefik_network

  # Add vectordb to the network if used
  vectordb:
    networks:
      - traefik_network

  # Add RAG API to the network if used
  rag_api:
    networks:
      - traefik_network

  traefik:
    image: traefik:v3.0
    ports:
      - "7000:80"
      - "7443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs"
    networks:
      - traefik_network
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--tls.certificates.certFile=/certs/domain.cert.pem"
      - "--tls.certificates.keyFile=/certs/private.key.pem"

networks:
  traefik_network:
    external: true
