apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-health
spec:
  type: ClusterIP
  selector: # whatever
  ports:
    - name: healthz
      port: 80
      targetPort: 10254
---
apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  rules:
    - host: elb-1234.example.com
      http:
        path: /healthz
        backend:
          serviceName: ingress-nginx-health
          servicePort: healthz
