## Dynamic configuration
http:
  routers:
    my-router:
      rule: "Path(`/foo`)"
      service: ealen
      entrypoints:
        - web
  services:
    ealen:
      loadBalancer:
        servers:
          - url: "http://echo-server:80"
