apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::405350004483:role/HRI-BIGEKS-TEST-rTestEksNodeInstanceRole-WhtCrrr7LYoG
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-20T21:13:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1354"
  uid: e146595f-a864-44d8-838e-b5116e95c237
