export PATH="${USERHOME}/.local/bin:${USERHOME}/go/bin:${USERHOME}/.cargo/bin:${USERHOME}/.nvim/bin:/usr/local/bin:/usr/bin:/bin"
set -o vi
alias l='ls -alF --color=auto'
alias v='vim'
alias g='grep -i'
bind 'set show-all-if-ambiguous on'
bind 'set show-all-if-unmodified on'
bind 'set completion-ignore-case on'
bind '"jj": vi-movement-mode'
bind '"\\t": menu-complete'
bind -m vi-command ".":yank-last-arg
bind 'set show-mode-in-prompt on'
bind 'set bell-style none'
bind 'set colored-stats On'
bind 'set menu-complete-display-prefix On'
bind 'set colored-completion-prefix On'
bind 'set mark-directories on'
bind 'set mark-symlinked-directories On'
bind 'set visible-stats On'
