FROM python:3.11-slim
WORKDIR /app
RUN pip install uv
CMD ["uvx", "--with", "mcp<2", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "uvx", "--with", "mcp<2",  "mcp-proxy", "--transport", "streamablehttp", "https://knowledge-mcp.global.api.aws"]
