services:
  mock-service:
#   image: nicolaka/netshoot # or any image with nc installed
    image: busybox # or any image with nc installed
    command:
      - sh
      - -c
      - |
        printf 'HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 4\r\nConnection: close\r\n\r\ntest' > /tmp/reply
        while true; do nc -lp 8088 < /tmp/reply; done
    ports:
      - "8088:8088"
    networks:
      - red-net
      - blue-net
      - orange-net

#   nginx-1:
#     image: nginx:latest
#     networks:
#       - red-net
# 
#   nginx-2:
#     image: nginx:latest
#     networks:
#       - blue-net
#       - orange-net

networks:
  red-net:
  blue-net:
  orange-net:
