services:

  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    healthcheck:
#      test: ["CMD", "curl", "---fail", "http://it-tools"]
      test: ["CMD", "curl", "-s", "localhost"]
      interval: 15s
      timeout: 10s
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ittools.rule=Host(`ittools.xaax.dev`)"
      - "traefik.http.routers.ittools.entrypoints=websecure"
      - "traefik.http.routers.ittools.tls=true"
      - "traefik.http.services.ittools.loadbalancer.server.port=80"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
