AWSTemplateFormatVersion: "2010-09-09"
Description: "TLS Certificate Secret for AWS Application Load Balancer"

Parameters:
  TlsCertificate:
    Type: String
    Description: "The TLS certificate (PEM format)"
    NoEcho: true
  
  TlsPrivateKey:
    Type: String
    Description: "The TLS private key (PEM format)"
    NoEcho: true
  
  SecretName:
    Type: String
    Description: "Name for the secret in AWS Secrets Manager"
    Default: "alb-tls-certificate"

Resources:
  TLSCertificateSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: "TLS certificate and key for AWS Application Load Balancer"
      SecretString: !Sub |
        {
          "tls.crt": "${TlsCertificate}",
          "tls.key": "${TlsPrivateKey}"
        }
      Tags:
        - Key: Purpose
          Value: ALB-TLS

Outputs:
  SecretArn:
    Description: "ARN of the created secret"
    Value: !Ref TLSCertificateSecret
    
  SecretName:
    Description: "Name of the created secret"
    Value: !Ref SecretName

