model: anth
functions: /home/loon/gitdir/skel/llm/WEATHER/weather_tool-better.py
system_fragments:
  - /home/loon/gitdir/skel/PROMPT/DEFAULT_PROMPT_strict.txt
tools:
  - llm_version
  - llm_time
  - simple_eval
  - web_search
