model_list:
  - model_name: bedrock-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-6
      aws_region_name: us-east-1
      aws_profile_name: bedrock
  - model_name: bedrock-haiku
    litellm_params:
      model: bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_region_name: us-east-1
      aws_profile_name: bedrock
  - model_name: bedrock-opus
    litellm_params:
      model: bedrock/us.anthropic.claude-opus-4-7
      aws_region_name: us-east-1
      aws_profile_name: bedrock
  - model_name: claude-opus-4-6
    litellm_params:
      model: anthropic/claude-opus-4-6
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: anthropic/claude-sonnet-4-6
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/claude-haiku-4-5-20251001
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: tinfoil-kimi-2-5
    litellm_params:
      model: openai/confidential-kimi-k2-5
      api_base: http://127.0.0.1:8080/v1
      api_key: os.environ/TINFOIL_API_KEY
#  set L
#  general_settings:
#    master_key: os.environ/LITELLM_MASTER_KEY
