services:
  drawio:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio.rule=Host(`drawio.xaax.dev`)"
      - "traefik.http.routers.drawio.entrypoints=websecure"
      - "traefik.http.routers.drawio.tls=true"
      - "traefik.http.services.drawio.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_web"
    networks:
      - traefik_web
    ports: !reset [] 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  traefik_web:
    external: true
