services:
  pacoloco:
    container_name: pacoloco
    image: ghcr.io/anatol/pacoloco
    ports:
      - "9129:9129"
    # volumes attibute within the 'services top-level element'
    volumes:
      - 
    environment:
      - TZ=America/New_York

# Top-level volumes declaration
volumes:
  pacoloco-data:
