apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
stringData:
  CREDS_KEY: 9830a71903696bfa85169
  JWT_SECRET: 7f276c85682318d3520
  JWT_REFRESH_SECRET: baddbdc474
  MEILI_MASTER_KEY: 97a5cf4113c
  OPENROUTER_KEY: sk-or-v1-996
